#pragma once
#include <Arduino.h>

#define LF_RX RX
#define LF_TX TX

#define LOW_FREQUENCY_DATA_IN RX

#define LED_POWER_RED_GPIO GPIO_NUM_32
#define LED_POWER_GREEN_GPIO GPIO_NUM_33 
#define LED_POWER_BLUE_GPIO GPIO_NUM_15

#define LED_STATUS_RED_GPIO GPIO_NUM_27
#define LED_STATUS_GREEN_GPIO GPIO_NUM_13
#define LED_STATUS_BLUE_GPIO GPIO_NUM_12

#define BUZZER_GPIO GPIO_NUM_14
#define RELAY_GPIO GPIO_NUM_22

#define HF_SS_PIN 21
#define HF_RST_PIN 26

#define INDICATOR_LEDC_CHAN_B 9
#define INDICATOR_LEDC_CHAN_P_RED 10
#define INDICATOR_LEDC_CHAN_P_GREEN 11
#define INDICATOR_LEDC_CHAN_P_BLUE 12
#define INDICATOR_LEDC_CHAN_S_RED 13
#define INDICATOR_LEDC_CHAN_S_GREEN 14
#define INDICATOR_LEDC_CHAN_S_BLUE 15

#define INDICATOR_BUZZER_GOOD_FREQ 6000
#define INDICATOR_BUZZER_BAD_FREQ 200
#define POWER_BLINK_RATE_SLOW 180000
#define POWER_BLINK_RATE_FAST 100000

#define LONG_BADGE_DURATION 420000
#define LONG_BADGE_RATE 70000

#define SHORT_BADGE_DURATION 400000

