#pragma once
#include <Arduino.h>

void setupGPIO()
{
    PIN_FUNC_SELECT(GPIO_PIN_MUX_REG[LED_POWER_RED_GPIO], PIN_FUNC_GPIO);
    gpio_set_direction(LED_POWER_RED_GPIO, GPIO_MODE_OUTPUT);

    PIN_FUNC_SELECT(GPIO_PIN_MUX_REG[LED_POWER_GREEN_GPIO], PIN_FUNC_GPIO);
    gpio_set_direction(LED_POWER_GREEN_GPIO, GPIO_MODE_OUTPUT);

    PIN_FUNC_SELECT(GPIO_PIN_MUX_REG[LED_POWER_BLUE_GPIO], PIN_FUNC_GPIO);
    gpio_set_direction(LED_POWER_BLUE_GPIO, GPIO_MODE_OUTPUT);

    PIN_FUNC_SELECT(GPIO_PIN_MUX_REG[LED_STATUS_RED_GPIO], PIN_FUNC_GPIO);
    gpio_set_direction(LED_STATUS_RED_GPIO, GPIO_MODE_OUTPUT);

    PIN_FUNC_SELECT(GPIO_PIN_MUX_REG[LED_STATUS_GREEN_GPIO], PIN_FUNC_GPIO);
    gpio_set_direction(LED_STATUS_GREEN_GPIO, GPIO_MODE_OUTPUT);

    pinMode(LED_STATUS_BLUE_GPIO, OUTPUT);

    PIN_FUNC_SELECT(GPIO_PIN_MUX_REG[BUZZER_GPIO], PIN_FUNC_GPIO);
    gpio_set_direction(BUZZER_GPIO, GPIO_MODE_OUTPUT);

    PIN_FUNC_SELECT(GPIO_PIN_MUX_REG[RELAY_GPIO], PIN_FUNC_GPIO);
    gpio_set_direction(RELAY_GPIO, GPIO_MODE_OUTPUT);
}
